<?php

use App\Modules\tao\Config\Data;
use App\Modules\tao\Models\SystemMenu;
use App\Modules\tao\Models\SystemNode;
use App\Modules\tao\sdk\phaxui\Layui\LayuiData;
use Phax\Foundation\AppService;

/**
 * @var \App\Modules\tao\Helper\MyMvcHelper $vv
 */
//$vv->print();
$list = SystemMenu::queryBuilder()
//    ->int('status', 1) 允许显示隐藏的菜单（否则隐藏子菜单会丢失关联）
        ->notEqual('pid', Data::HOME_PID)
        ->columns('id,pid,title')
        ->find();
$optionList = LayuiData::selectOptions(0, $list);
$menuList = array_merge([
        [
                'id' => 0,
                'pid' => 0,
                'title' => '顶级菜单'
        ]
], $optionList);
$pid = $vv->pick('pid', AppService::request()->getQuery('pid', 0));
$id = $vv->pick('id', 0);
$html = $vv->html();
?>

<form class="layui-form">

    <div class="layui-form-item  layui-row layui-col-xs12">
        <label class="layui-form-label required">上级菜单</label>
        <div class="layui-input-inline">
            <select name="pid">
                <?php
                foreach ($menuList as $vo) { ?>
                    <option value="<?php
                    echo $vo['id'] ?>"
                            <?php
                            echo $pid == $vo['id'] ? 'selected' : '' ?>
                    ><?php
                        echo $vo['title'] ?></option>
                    <?php
                } ?>
            </select>
        </div>
    </div>

    <?php echo $vv->layuiForm()->input('菜单名称', 'title', value: $vv->pick('title'), required: true,
            aux: '通常为中文名称，用户可见') ?>
    <div class="layui-form-item">
        <?= $vv->layuiForm()->input('访问角色', 'roles', value: $vv->pick('roles'), formItem: false) ?>

        <div class="layui-input-inline" style="width: 300px;padding-top: 4px;">
            <a class="layui-btn layui-btn-sm layui-btn-warm" onclick="inputRoles('')">清空</a>
            <?php
            foreach (Data::MapAccess as $v => $text) { ?>
                <a class="layui-btn layui-btn-sm"
                   onclick="inputRoles('<?= $v ?>')"><?= $text ?></a>
                <?php
            } ?>
        </div>
    </div>
    <?=
    $vv->layuiForm()->input('链接地址', 'href', value: $vv->pick('href'),aux: '格式：模块名/控制器/方法，不要省略方法 index');
    ?>
    <?php echo
    $vv->layuiForm()->radio('地址前缀', 'type', vtOptions: [
            0 => '无',
            SystemNode::KIND_MODULE => 'M 模块',
            SystemNode::KIND_PROJECT => 'P 项目'
    ], value: $vv->pick('type', 0), aux:'选择 `M 模块` 自动为链接补充前缀 /m/，选择 `P 项目` 则补充前缀 /p/' ) ?>


    <?php echo $vv->layuiHtml()->icon($vv->pick('icon')); ?>


    <div class="layui-form-item">
        <label class="layui-form-label">菜单排序</label>
        <div class="layui-input-inline">
            <input type="number" name="sort"
                   lay-reqtext="菜单排序不能为空" placeholder="请输入菜单排序"
                   value="<?php
                   echo $vv->pick('sort', 0) ?>" class="layui-input">
        </div>
    </div>


    <div class="layui-form-item text-center">
        <button type="submit" class="layui-btn layui-btn-normal layui-btn-sm" lay-submit>确认</button>
        <button type="reset" class="layui-btn layui-btn-primary layui-btn-sm">重置</button>
    </div>

</form>
<?php
$vv->layui()->addWindowConfig([])->footer();

echo $vv->layuiHtml()->iconJs();
?>
<script>
    admin.form.submitFirst(() => {
        admin.iframe.close(true);
    })
    const inputEle = $('#inputRoles');


    function inputRoles(v) {
        inputEle.val(v);
    }
</script>
