#!/usr/bin/env php
<?php

use phpseclib3\Net\SFTP;

$testPrefix = 'local-test-'; // 用于测试

// 判断操作系统
const IS_WIN = PHP_OS_FAMILY === 'Windows';
const PATH_ROOT = __DIR__ . '/';
const PATH_SRC = __DIR__ . '/src/';
const PATH_MAINTAIN_tmp = __DIR__ . '/maintain.tmp.txt';

class G
{
    public array $maintainData = [];
    public array $argsOptions = [];
    public string $projectName = '';
    public string $action = '';

    public function __construct()
    {
        include_once __DIR__ . '/src/tao996/phar/dotenv.phar';
        spl_autoload_register(function ($class) {
            if (str_starts_with($class, 'Phax\\')) {
                include_once PATH_SRC . 'tao996/' . str_replace('\\', '/', $class) . '.php';
            }
        });
        $this->projectName = pathinfo(__DIR__, PATHINFO_BASENAME);
        $this->maintainData = $this->getMaintainTmp();
        $this->argsOptions = $this->loadKvArgs();
        $this->loadEnv();
    }

    /**
     * 获取 .env 配置信息
     * @return void
     */
    private function loadEnv(): void
    {
        global $testPrefix;
        $dotenv = new \Symfony\Component\Dotenv\Dotenv();
        if (!file_exists(__DIR__ . '/' . $testPrefix . '.env')) {
            return;
        }
        $dotenv->overload(__DIR__ . '/' . $testPrefix . '.env');
    }


    /**
     * 获取命令行中的 --key=value 或者 -key=value 或者 -key 参数
     * @return array
     */
    private function loadKvArgs(): array
    {
        global $argv;
        $args = $argv;
        array_shift($args); // 移除脚本名称

        $this->action = $args[0] ?? 'help';

        $options = [];
        foreach ($args as $item) {
            if (preg_match('/^(--?)([\w-]+)=(.*)$/', $item, $matches)) {
                $value = $matches[3];
                $key = ltrim($matches[2], "-");
                $options[$key] = $value;
            } elseif (preg_match('/^(--?)([\w-]+)$/', $item, $matches)) {
                $key = ltrim($matches[2], "-");
                $options[$key] = null;
            }
        }
        return $options;
    }


    /**
     * 获取当前命令所保存的配置信息，用于在无指定参数时使用
     * @return array
     */
    private function getMaintainTmp(): array
    {
        if (file_exists(PATH_MAINTAIN_tmp)) {
            return json_decode(file_get_contents(PATH_MAINTAIN_tmp), true);
        }
        return [];
    }

    /**
     * 保存命令行所指定的数据
     * @return void
     */
    function saveMaintainTmp(): void
    {
        file_put_contents(PATH_MAINTAIN_tmp, json_encode($this->maintainData));
    }

    /**
     * 命令行中是否存在参数
     * @param string $key
     * @return bool
     */
    public function hasArgsWithKey($key): bool
    {
        return array_key_exists($key, $this->argsOptions);
    }

    /**
     * 获取参数中的值
     * @param string $key
     * @param mixed $default
     * @param bool $int 是否转为整型
     * @return int|mixed|string
     */
    public function getArgsWithKey($key, $default = '', $int = false): mixed
    {
        $data = $this->argsOptions[$key] ?? $this->maintainData[$key] ?? $default;
        return $int ? intval($data) : $data;
    }

    /**
     * 读取指定的文件
     * @param string $filePath 文件路径
     * @param string $filterStart 不要读取以此字符开头的行
     * @return string
     */
    function readFileWith($filePath, $filterStart = '#'): string
    {
        $fileHandle = fopen($filePath, 'r');

        if ($fileHandle === false) {
            die("无法打开文件: $filePath");
        }

        $filteredLines = [];

        while (($line = fgets($fileHandle)) !== false) {
            $line = trim($line);
            if (!str_starts_with($line, $filterStart)) {
                $filteredLines[] = $line;
            }
        }

        fclose($fileHandle);
        return join(PHP_EOL, $filteredLines);
    }
}

$g = new G();

const ActionInitFiles = [
    // .env.example 手动生成
    'docker-compose.example.yaml',
    'php/php.example.ini',
    'php/supervisord.example.conf',

    'src/.env.example',
    'src/phpunit.example.xml',
    'src/config/config.example.php',
    'src/config/project.example.php'
];
const SshData = [
    'ip' => '',
    'port' => 22,
    'username' => '',
    'password' => '', // ssh2/sftp 密码登录
    'private_ssh_key' => '', // ssh2/sftp 证书登录
    'path' => 'path/of/phalcon-admin', // 当前项目在线上服务器所映射的目录
    'nginx' => '/etc/nginx/conf.d/',
    'certs' => ['key' => '', 'pem' => ''], // 上传到 nginx 目录的证书，要保存在 nginx/ssl 目录下
    'hosts' => [], // 添加到 /etc/hosts 的域名列表；示例 [a1.test,www.a1.test]
    'logs' => [ // 需要下载的日志
        'log/nginx/access.log',
        'log/nginx/error.log',
        'php/php_errors.log',
        ['src/storage/logs'] // 数组表示一个目录
    ],
    'backup' => [],// 其它需要备份的文件，在执行 php maintain prod -d 时也会一同下载
    // 以下字段由系统自动更新，不需要更新
    'projects' => [],
];

switch ($g->action) {
    case 'init':
        class ActionInit
        {
            private bool $overwrite = false;

            public function __construct(public G $g)
            {
                $port = $g->getArgsWithKey('port', 0, true);
                if ($port < 1) {
                    die('必须指定端口号 -port=9988' . PHP_EOL);
                }
                $g->maintainData['port'] = $port;

                $this->overwrite = $g->hasArgsWithKey('y');
            }

            public function createEnvFile(): void
            {
                global $testPrefix;
                $newEnvFilePath = __DIR__ . '/' . $testPrefix . '.env';
                if (file_exists($newEnvFilePath) && !$this->overwrite) {
                    echo '跳过文件 {' . $testPrefix . '.env}', PHP_EOL;
                } else {
                    $envContent = file_get_contents(__DIR__ . '/.env.example');
                    $envContent = str_replace(
                        'OPEN_PORT=8071',
                        'OPEN_PORT=' . $this->g->maintainData['port'],
                        $envContent
                    );
                    $envContent = str_replace('APP_NAME=phax', 'APP_NAME=' . $this->g->projectName, $envContent);
                    file_put_contents($newEnvFilePath, $envContent);
                    echo '复制成功 {' . $testPrefix . '.env}', PHP_EOL;
                }
            }

            private function copyExample($example): void
            {
                global $testPrefix;
                if (!file_exists($example)) {
                    die('找不到文件:' . $example . PHP_EOL);
                }

                $info = pathinfo($example);
                $toName = $info['dirname'] . '/' . $testPrefix . str_replace('.example', '', $info['basename']);
                $title = str_replace(__DIR__ . '/', '', $toName);

                if (file_exists($toName) && !$this->overwrite) {
                    echo '跳过文件 {' . $title . '}', PHP_EOL;
                    return;
                }


                if (copy($example, $toName)) {
                    echo '复制成功 {', $title . '}', PHP_EOL;
                }
            }

            public function copyFiles(): void
            {
                foreach (ActionInitFiles as $file) {
                    $this->copyExample(PATH_ROOT . $file);
                }
            }

            public function replaceDockerComposeImage(): void
            {
                global $testPrefix;
                $dcYaml = PATH_ROOT . $testPrefix . 'docker-compose.yaml';
                $g = $this->g;
                if ($g->hasArgsWithKey('cn') || (isset($g->maintainData['cn']) && $g->maintainData['cn'])) {
                    $dcYamlContent = file_get_contents($dcYaml);
                    $dcYamlContent = str_replace(
                        'image: authus/phalcon:',
                        'image: registry.cn-shenzhen.aliyuncs.com/authus/phalcon:',
                        $dcYamlContent
                    );
                    file_put_contents($dcYaml, $dcYamlContent);
                    $g->maintainData['cn'] = true;
                }
            }
        }

        $action = new ActionInit($g);
        $action->createEnvFile();
        $action->copyFiles();
        $action->replaceDockerComposeImage();

        echo 'SUCCESS.', PHP_EOL;
        break;
    case 'clear':
        class ActionClear
        {
            public array $toDeleteFiles = [];

            public function __construct(public G $g)
            {
                foreach (array_merge(['.env.example'], ActionInitFiles) as $file) {
                    $this->toDeleteFiles[] = $this->reverseCopyExample(PATH_ROOT . $file);
                }
            }

            private function reverseCopyExample($example): string
            {
                global $testPrefix;
                $info = pathinfo($example);
                return $info['dirname'] . '/' . $testPrefix . str_replace('.example', '', $info['basename']);
            }

            public function deleteFiles(): void
            {
                foreach ($this->toDeleteFiles as $file) {
                    if (file_exists($file)) {
                        $title = str_replace(PATH_ROOT, '', $file);
                        if (unlink($file)) {
                            echo '删除成功 {', $title, '}', PHP_EOL;
                        } else {
                            echo '删除失败 {', $title, '}', PHP_EOL;
                        }
                    } else {
                        echo '文件不存在 {', $file, '}', PHP_EOL;
                    }
                }
            }

            public function printDeleteFiles()
            {
                return array_map(function ($file) {
                    return str_replace(PATH_ROOT, '', $file);
                }, $this->toDeleteFiles);
            }
        }

        $action = new ActionClear($g);
        if ($g->hasArgsWithKey('y')) {
            $action->deleteFiles();
        } else {
            print_r($action->printDeleteFiles());
            echo '检查上面的文件，如果没有问题，则可使用 -y 进行删除', PHP_EOL;
        }
        break;
    case "backup":
        echo "TODO 备份外部数据库", PHP_EOL;
        break;
    case "prod":
        define('PATH_NGINX_SSL', PATH_ROOT . 'nginx/ssl/');

        class ActionProd
        {
            /**
             * 目录名称，默认为 default
             * @var string|int|mixed
             */
            public string $dir = '';
            public string $path_prod = __DIR__ . '/prod/';
            /**
             * 配置目录路径 `$path_prod.$dir`，默认 `__DIR__./prod/default/`
             * @var string
             */
            public string $path_prod_save = '';
            /**
             * 远程服务器文件路径，默认 `__DIR__./prod/default/ssh.php`
             * @var string
             */
            public string $path_prod_config_file = '';
            /**
             * nginx 站点返回，默认 `__DIR__./prod/default/$projectName.conf`
             * @var string
             */
            public string $path_prod_host_file = '';
            public string $path_prod_logs = __DIR__ . '/prod/logs/';
            public array $files = [
                '.env.example',
                'docker-compose.example.yaml',
                'php/php.example.ini',
                'php/supervisord.example.conf',
                'src/.env.example',
                'src/config/config.example.php',
                'src/config/project.example.php',
                'src/config/migration.example.php',
                'nginx/sites/default.example.conf', // 如果使用这个文件，则需要修改 docker-compose.yaml
            ];
            public array $nginxFiles = []; // 站点配置
            /**
             * ssh.php 的配置信息
             * @return array{ip:string,port:int,username:string,password:string,public_ssh_key:string,private_ssh_key:string,path:string,nginx:string,
             *     certs:array{key:string,pem:string},hosts:array{string}}
             */
            private array $config = [];
            public string $remotePhalconAdminPath = '';
            public string $remoteNginxConf = '';

            public function __construct(public G $g)
            {
                $this->dir = $g->getArgsWithKey('dir', 'default');
                $this->path_prod_save = $this->path_prod . $this->dir . '/';
                $this->path_prod_host_file = $this->path_prod_save . $g->projectName . '.conf';
                $this->path_prod_config_file = $this->path_prod_save . 'ssh.php';

                $this->nginxFiles = [
                    ['nginx/host.example.conf', $g->projectName . '.conf'],
                    ['nginx/host.location.example.conf', $g->projectName . '.location.conf']
                ];
            }

            /**
             * 获取 `$this->files[i]` 保存在 prod 目录时的文件路径
             * @param string|array{string,string} $file
             * @param string|null $localPath 本地保存目录，默认为 `$this->path_prod_save`
             * @return string
             */
            public function getLocalFile($file, $localPath = null)
            {
                if (is_null($localPath)) {
                    $localPath = $this->path_prod_save;
                }
                if (is_array($file)) {
                    return $localPath . $file[1];
                }
                return $localPath . str_replace('/', '_', str_replace('.example', '', $file));
            }

            /**
             * 获取 `$this->files[i]` 在远程文件路径
             * @param string|array{string,string} $file
             * @param string|null $remotePath 远程对应的目录，默认来自 ssh.php->path
             * @return string 示例 `xxx/.env` 或者 `xxx/src/config/config.php`
             */
            public function getRemoteFile($file, $remotePath = null)
            {
                if (is_null($remotePath)) {
                    $remotePath = $this->remotePhalconAdminPath;
                }
                if (is_array($file)) {
                    return $remotePath . $file[1];
                }
                return $remotePath . str_replace('.example', '', $file);
            }

            /**
             * @return array{ip:string,port:int,username:string,password:string,public_ssh_key:string,private_ssh_key:string,path:string,nginx:string,
             *     certs:array{key:string,pem:string},hosts:array{string}}
             */
            public function getConfig(): array
            {
                if (empty($this->config)) {
                    if (!file_exists($this->path_prod_save)) {
                        die('目录不存在 ' . $this->path_prod_save . PHP_EOL);
                    }
                    $this->config = include_once $this->path_prod_config_file;
                    $this->remotePhalconAdminPath = rtrim($this->config['path'], '/') . '/';
                    $this->remoteNginxConf = rtrim($this->config['nginx'] ?? '/etc/nginx/cond.f', '/') . '/';
                }
                return $this->config;
            }

            public function getConfigWith($key, $default = '')
            {
                return $this->getConfig()[$key] ?? $default;
            }

            public function getCerts()
            {
                $certs = [];
                foreach ($this->config['certs'] ?? [] as $cert) {
                    $file = PATH_ROOT . 'nginx/ssl/' . $cert;
                    if (is_file($file) && file_exists($file)) {
                        $certs[] = $cert;
                    }
                }
                return $certs;
            }

            public function getHosts()
            {
                return $this->config['hosts'] ?? [];
            }

            public function createConfig()
            {
                $data = SshData;
                if (file_exists($this->path_prod_config_file)) {
                    $data = array_merge($data, include_once $this->path_prod_config_file);
                }
                $this->updateConfigFile($data);
            }

            public function updateConfigFile($data)
            {
                file_put_contents($this->path_prod_config_file, '<?php return ' . var_export($data, true) . ';');
            }

            // 项目最新上传的时间
            public function getProjectMtime($project)
            {
                $projects = $this->getConfigWith('projects', []);
                return $projects[$project] ?? 0;
            }

            public function updateProjectMtime($project)
            {
                $projects = $this->getConfigWith('projects', []);
                $projects[$project] = time();
                $this->config['projects'] = $projects;
                $this->updateConfigFile($this->config);
            }

            public function hasFilesInSaveDir()
            {
                if (is_dir($this->path_prod_save)) {
                    return glob($this->path_prod_save . '*');
                }
                return false;
            }

            public function createProdSaveDir()
            {
                if (is_dir($this->path_prod_save)) {
                    $hasFiles = glob($this->path_prod_save . '*');
                    if ($this->g->hasArgsWithKey('c')) {
                        if ($hasFiles && !$this->g->hasArgsWithKey('y')) {
                            die('{prod/' . $this->dir . '} 目录不为空；如需覆盖请追加参数 -y' . PHP_EOL);
                        }
                    } elseif (!$hasFiles) {
                        die('{prod/' . $this->dir . '} 目录为空，请先使用参数 -c 使用' . PHP_EOL);
                    }
                } else {
                    mkdir($this->path_prod_save);
                }
            }

            public function createFiles(): void
            {
                foreach (array_merge($this->files, $this->nginxFiles) as $file) {
                    if (is_string($file)) {
                        $toName = str_replace('.example', '', $file);
                    } else {
                        $toName = $file[1];
                        $file = $file[0];
                    }
                    $pathToName = $this->path_prod_save . str_replace('/', '_', $toName);
                    if (copy(PATH_ROOT . $file, $pathToName)) {
                        echo '复制成功 {', $toName . '}', PHP_EOL;
                    } else {
                        echo '复制失败 {', $toName . '}', PHP_EOL;
                        die();
                    }
                }
            }
        }

        $action = new ActionProd($g);
        $action->createProdSaveDir();

        if ($g->hasArgsWithKey('c')) {
            $type = $g->getArgsWithKey('c', '');
            if ($type == '*' || !$action->hasFilesInSaveDir()) {
                $action->createFiles();
            }
            $action->createConfig();

            echo "生成完毕，请修改你的 ssh.php，然后再次执行命令 `php maintain prod -r -y`，将自动更新配置", PHP_EOL;
        } elseif ($g->hasArgsWithKey('r')) {
            class ActionProdReplace
            {

                public function __construct(public ActionProd $prod)
                {
                    if (!file_exists($this->prod->path_prod_save . 'ssh.php')) {
                        die('ssh.php 文件不存在');
                    }
                    $this->prod->getConfig();
                }

                // 更改 host 文件中的 xxx.test
                function replaceNginxHost(): void
                {
                    $hostContent = file_get_contents($this->prod->path_prod_host_file);

                    $domains = $this->prod->getHosts();

                    // phalcon-admin.conf
                    // 1。替换域名
                    if ($domains) {
                        $dbDomains = array_map(function ($domain) {
                            return str_starts_with($domain, 'www.')
                                ? str_replace('www.', 'www.db-', $domain)
                                : 'db-' . $domain;
                        }, $domains);
                        $hostContent = str_replace('db-xxx.test', join(' ', $dbDomains), $hostContent);
                        $hostContent = str_replace('xxx.test', join(' ', $domains), $hostContent);
                        echo '替换域名成功 {', $this->prod->g->projectName, '.conf}', PHP_EOL;
                    }
                    $phpmyadminPort = $_ENV['PHPMYADMIN_PORT'] ?? 0;
                    if ($phpmyadminPort > 0) {
                        $hostContent = str_replace(':5456', ':' . $phpmyadminPort, $hostContent);
                        echo '替换 db 端口成功', PHP_EOL;
                    }
                    // 2。替换 include
                    $hostContent = str_replace(
                        'include host.location.example.conf;',
                        'include conf.d/' . $this->prod->g->projectName . '.location.conf',
                        $hostContent
                    );
                    // 3. 替换证书
                    $certs = $this->prod->getCerts();
                    if ($certs) {
                        if (!empty($certs['key'])) {
                            $hostContent = str_replace('xxx.key', $certs['key'], $hostContent);
                            echo '替换 key 证书成功', PHP_EOL;
                        }
                        if (!empty($certs['pem'])) {
                            $hostContent = str_replace('xxx.pem', $certs['pem'], $hostContent);
                            echo '替换 pem 证书成功', PHP_EOL;
                        }
                    }
                    file_put_contents($this->prod->path_prod_host_file, $hostContent);

                    // phalcon-admin.location.conf
                    if ($port = $this->getPort()) {
                        $path_location_file = $this->prod->path_prod_save . $this->prod->g->projectName . '.location.conf';
                        $locationContent = file_get_contents($path_location_file);
                        $locationContent = str_replace(':8071', ':' . $port, $locationContent);
                        file_put_contents($path_location_file, $locationContent);
                        echo '替换端口成功 {', $this->prod->g->projectName . '.location.conf', '}', PHP_EOL;
                    }
                }

                public function getPort()
                {
                    $port = intval($this->prod->g->maintainData['port'] ?? 0);
                    return $port > 0 && $port != 8071 ? $port : 0;
                }

                public function replaceEnv()
                {
                    if ($port = $this->getPort()) {
                        $envContent = file_get_contents($this->prod->path_prod_save . '.env');
                        $envContent = str_replace('OPEN_PORT=8071', 'OPEN_PORT=' . $port, $envContent);
                        file_put_contents($this->prod->path_prod_save . '.env', $envContent);
                    }
                }
            }

            $replace = new ActionProdReplace($action);
            $replace->replaceEnv();
            $replace->replaceNginxHost();

            echo '替换完成', PHP_EOL;
        }

        class ActionProdServer
        {
            // https://phpseclib.com/docs/auth

            public function __construct(public array $config)
            {
                $this->validate();
                include_once __DIR__ . '/src/tao996/phar/phpseclib.phar';
            }

            private function validate(): void
            {
                if (empty($this->config['path'])) {
                    die('必须指定远程保存地址 ssh.php->path');
                }
                if (empty($this->config['ip'])) {
                    die('必须指定 ssh ip 地址' . PHP_EOL);
                } elseif (empty($this->config['username'])) {
                    die('必须指定 ssh username' . PHP_EOL);
                } elseif (empty($this->config['password']) && empty($this->config['private_ssh_key'])) {
                    die('必须指定密码或者登录证书');
                }
            }

            private function sftp()
            {
                static $sftp = null;
                if (is_null($sftp)) {
                    $sftp = new phpseclib3\Net\SFTP($this->config['ip']);
                    if (!empty($this->config['password'])) {
                        if (!$sftp->login($this->config['username'], $this->config['password'])) {
                            die('SFTP 密码登录失败');
                        }
                    } else {
                        $key = \phpseclib3\Crypt\PublicKeyLoader::load(
                            file_get_contents($this->config['private_ssh_key'])
                        );
                        if (!$sftp->login($this->config['username'], $key)) {
                            die('SFTP Public Key 登录失败');
                        }
                    }
                }
                return $sftp;
            }

            private function ssh2()
            {
                static $ssh = null;
                if (is_null($ssh)) {
                    $ssh = new \phpseclib3\Net\SSH2($this->config['ip']);
                    if (!empty($this->config['password'])) {
                        if (!$ssh->login($this->config['username'], $this->config['password'])) {
                            die("SSH2 validation failed using Username: " . $this->config['username'] . " (specify valid password)");
                        }
                    } else {
                        $key = \phpseclib3\Crypt\PublicKeyLoader::load(
                            file_get_contents($this->config['private_ssh_key'])
                        );
                        if (!$ssh->login(
                            $this->config['username'],
                            $key
                        )) {
                            die("SSH2 validation failed using Username: " . $this->config['username'] . " (specify valid SSH keys or check your SSH key path)");
                        }
                    }
                }
                return $ssh;
            }


            public function sendCommand($command): string|false
            {
                return $this->ssh2()->exec($command);
            }


            public function sendFile($local_file, $remote_file, $print = true): bool
            {
                if (!file_exists($local_file)) {
                    die('文件不存在 {' . $local_file . '}' . PHP_EOL);
                }
                $remote_dir = dirname($remote_file);
                if (!$this->sftp()->is_dir($remote_dir)) {
                    $this->createRemoteDirectoryRecursively($this->sftp(), $remote_dir);
                }
                $rst = $this->sftp()->put($remote_file, $local_file, SFTP::SOURCE_LOCAL_FILE);

                if ($print) {
                    if ($rst) {
                        echo '上传成功 {', $remote_file, '}', PHP_EOL;
                    } else {
                        echo '本地文件:', $local_file, PHP_EOL;
                        echo '远程文件:', $remote_file, PHP_EOL;
                        throw new \Exception('上传失败');
                    }
                }
                return $rst;
            }


            // 递归创建目录
            private function createRemoteDirectoryRecursively(SFTP $sftp, string $directory)
            {
                $parentDir = dirname($directory);
                if ($parentDir !== '.' && !$sftp->is_dir($parentDir)) {
                    $this->createRemoteDirectoryRecursively($sftp, $parentDir);
                }
                if (!$sftp->is_dir($directory)) {
                    $sftp->mkdir($directory);
                }
            }

            /**
             * 获取文件
             */
            public function recvFile($remote_file, $local_file, $print = true): bool
            {
                $rst = $this->sftp()->get($remote_file, $local_file);
                if ($print) {
                    if ($rst) {
                        echo '获取成功 {', $remote_file, '}', PHP_EOL;
                        echo '   =>{', $local_file, '}', PHP_EOL;
                    } else {
                        echo '获取失败 {', $remote_file, '}', PHP_EOL;
                    }
                }

                return $rst;
            }

            /**
             * 移除文件
             */
            public function delFile($remote_file, $print = true): bool
            {
                $rst = $this->sftp()->delete($remote_file);
                if ($print) {
                    if ($rst) {
                        echo '移除成功 {', $remote_file, '}', PHP_EOL;
                    } else {
                        echo '移除失败 {', $remote_file . '}', PHP_EOL;
                    }
                }
                return $rst;
            }

            private function skipDownloadFile($file)
            {
                return in_array($file, ['.', '..', '.gitignore']);
            }

            public function downloadDir($remote_dir, $local_dir)
            {
                $remote_dir = rtrim($remote_dir, '/') . '/';
                $local_dir = rtrim($local_dir, '/') . '/';

                $sftp = $this->sftp();
                if ($remoteList = $sftp->nlist($remote_dir)) {
                    foreach ($remoteList as $item) {
                        if (!$this->skipDownloadFile($item)) {
                            if ($sftp->is_dir($remote_dir . $item)) {
                                $localSubDir = $local_dir . $item;
                                if (!is_dir($localSubDir)) {
                                    mkdir($localSubDir, 0777, true);
                                }
                                // 递归下载
                                $this->downloadDirectoryRecursive($sftp, $remote_dir . $item, $localSubDir);
                            } else {
                                // 直接下载
                                $this->recvFile($remote_dir . $item, $local_dir . $item);
                            }
                        }
                    }
                }
            }

            private function downloadDirectoryRecursive(SFTP $sftp, string $remoteSubDir, string $localSubDir)
            {
                $remoteList = $sftp->nlist($remoteSubDir);
                if ($remoteList) {
                    foreach ($remoteList as $item) {
                        if (!$this->skipDownloadFile($item)) {
                            if ($sftp->is_dir($remoteSubDir . $item)) {
                                $newLocalSubDir = $localSubDir . $item;
                                if (!is_dir($newLocalSubDir)) {
                                    mkdir($newLocalSubDir, 0777, true);
                                }
                                $this->downloadDirectoryRecursive($sftp, $remoteSubDir . $item, $newLocalSubDir);
                            } else {
                                $localFilePath = $localSubDir . $item;
                                $remoteFilePath = $remoteSubDir . $item;
                                $this->recvFile($remoteFilePath, $localFilePath);
                            }
                        }
                    }
                }
            }
        }

        if ($g->hasArgsWithKey('u')) {
            $ssh = new ActionProdServer($action->getConfig());
            echo '待上传目录: prod/', $action->dir, PHP_EOL;

            $uValue = $g->getArgsWithKey('u', '*');

            if (in_array($uValue, ['*', 'app'])) {
                echo '准备上传项目配置文件...', PHP_EOL;
                foreach ($action->files as $file) {
                    $local_file = $action->getLocalFile($file);
                    $remote_file = $action->getRemoteFile($file);
                    $ssh->sendFile($local_file, $remote_file);
                }
            }
            if (in_array($uValue, ['*', 'nginx'])) {
                if (empty($ssh->sendCommand('which nginx'))) {
                    die("nginx 还没有安装作" . PHP_EOL);
                }
                echo '准备上传站点文件到 nginx...', PHP_EOL;

                foreach ($action->nginxFiles as $files) {
                    $ssh->sendFile(
                        $action->path_prod_save . $files[1],
                        $action->remoteNginxConf . $files[1]
                    );
                }

                echo '准备上传证书到 nginx...', PHP_EOL;
                foreach ($action->getCerts() as $cert) {
                    $ssh->sendFile(
                        PATH_NGINX_SSL . $cert,
                        $action->remoteNginxConf . $cert
                    );
                }
            }
            if (in_array($uValue, ['*', 'hosts', 'host'])) {
                echo '准备处理 /etc/hosts...', PHP_EOL;
                $content = $ssh->sendCommand('cat /etc/hosts');
                $appendHosts = [];
                foreach ($action->getHosts() as $host) {
                    if (!str_contains($content, $host)) {
                        $appendHosts[] = '127.0.0.1 ' . $host;
                    }
                }
                if (!empty($appendHosts)) {
                    $cmd = 'echo "' . join(PHP_EOL, $appendHosts) . PHP_EOL . '" >> /etc/hosts';
                    $ssh->sendCommand($cmd);
                    echo '写入完成 /etc/hosts', PHP_EOL;
                }
            }
        } elseif ($g->hasArgsWithKey('del')) {
            $ssh = new ActionProdServer($action->getConfig());

            $dValue = $g->getArgsWithKey('del', '*');
            if (in_array($dValue, ['*', 'app'])) {
                echo '准备移除项目配置文件...', PHP_EOL;
                foreach ($action->files as $file) {
                    $remote_file = $action->getRemoteFile($file);
                    $ssh->delFile($remote_file);
                }
            }
            if (in_array($dValue, ['*', 'nginx'])) {
                echo '准备移除配置到 nginx 的文件...', PHP_EOL;
                foreach ($action->nginxFiles as $files) {
                    $remote_file = $action->remoteNginxConf . $files[1];
                    $ssh->delFile($remote_file);
                }
                if ($certs = $action->getCerts()) {
                    echo '准备移除配置到 nginx 的证书...', PHP_EOL;
                    foreach ($certs as $cert) {
                        $remote_file = $action->remoteNginxConf . $cert;
                        $ssh->delFile($remote_file);
                    }
                }
            }
            if (in_array($dValue, ['*', 'hosts', 'host'])) {
                echo '准备移除 /etc/hosts 域名配置信息 ...', PHP_EOL;
                $hosts = $action->getHosts();
                if (!empty($hosts)) {
                    $content = $ssh->sendCommand('cat /etc/hosts');
                    if (str_contains($content, '"')) {
                        die('/etc/hosts 中包含双引号，请手动替换' . PHP_EOL);
                    }
                    foreach ($hosts as $host) {
                        $content = str_replace('127.0.0.1 ' . $host, '', $content);
                    }
                    $content = preg_replace('/\n{2,}/', "\n", $content);
                    $cmd = 'echo "' . $content . '" >> /etc/hosts';
                    $ssh->sendCommand($cmd);
                    echo '更新完成 /etc/hosts', PHP_EOL;
                }
            }
        } elseif ($g->hasArgsWithKey('log')) {
            echo '准备下载日志...', PHP_EOL;
            if ($logs = $action->getConfigWith('logs', [])) {
                $pathLog = $action->path_prod_logs . $action->dir . '/' . date('Ymd') . '/';
                if (!file_exists($pathLog)) {
                    mkdir($pathLog, 0777, true);
                }
                $ssh = new ActionProdServer($action->getConfig());
                foreach ($logs as $log) {
                    if (is_string($log)) {
                        $remote_file = $action->remotePhalconAdminPath . $log;
                        $local_file = $pathLog . str_replace('/', '_', $log);
                        $ssh->recvFile($remote_file, $local_file);
                    } elseif (is_array($log)) {
                        $ssh->downloadDir($action->remotePhalconAdminPath . $log[0], $pathLog);
                    }
                }
            } else {
                echo '没有配置下载日志...', PHP_EOL;
            }
        } elseif ($g->hasArgsWithKey('d')) { // 备份远程的配置文件
            $ssh = new ActionProdServer($action->getConfig());
            echo '备份项目配置文件...', PHP_EOL;
            $pathBackup = rtrim($action->path_prod_save, '/') . '_' . date('Ymd') . '/';
            if (!file_exists($pathBackup)) {
                mkdir($pathBackup);
            }

            foreach ($action->files as $file) {
                $remote_file = $action->getRemoteFile($file);
                $local_file = $action->getLocalFile($file, $pathBackup);
                $ssh->recvFile($remote_file, $local_file);
            }
            echo '备份 nginx 站点文件...', PHP_EOL;
            foreach ($action->nginxFiles as $files) {
                $ssh->recvFile(
                    $action->remoteNginxConf . $files[1],
                    $pathBackup . $files[1]
                );
            }
            if ($backups = $action->getConfigWith('backup', [])) {
                echo '备份自定义项目文件...', PHP_EOL;
                foreach ($backups as $file) {
                    $local_file = $pathBackup . str_replace('/', '_', $file);
                    $ssh->recvFile(
                        $action->remotePhalconAdminPath . $file,
                        $local_file
                    );
                }
            }

            echo '备份 ssh.php 文件...', PHP_EOL;
            copy(
                $action->path_prod_config_file,
                $pathBackup . 'ssh.php'
            );

            echo '完成备份 {', $pathBackup, '}', PHP_EOL;
        } elseif ($g->hasArgsWithKey('project')) {
            $project = $g->getArgsWithKey('project', '');
            if (empty($project)) {
                die('必须指定待推送的项目名称' . PHP_EOL);
            }
            $path_project = PATH_SRC . 'App/Projects/' . $project . '/';
            if (!is_dir($path_project)) {
                die('待推送项目不存在 {' . $project . '}' . PHP_EOL);
            }
            $ssh = new ActionProdServer($action->getConfig());
            $files = \Phax\Utils\MyFileSystem::getFilesInDirectory($path_project);
            $remote_dir = $action->remotePhalconAdminPath . 'src/';
            $lastMtime = $action->getProjectMtime($project);
            foreach ($files as $file) {
                $mtime = filemtime($file);
                if ($mtime > $lastMtime) {
                    $remote_file = $remote_dir . str_replace(PATH_SRC, '', $file);
                    $ssh->sendFile($file, $remote_file);
                }
            }
            $action->updateProjectMtime($project);
            echo '上传项目完毕', PHP_EOL;
        }

        break;
    case 'help':
        echo "~~~~~~~~~~ HOW TO USE ~~~~~~~~~~", PHP_EOL;
        echo <<<HELP
-y : 默认情况下如果 nginx 目录下存在着站点的配置文件，则不会自动生成

php maintain init       # 根据当前目录初始化环境
    -port=Num   : nginx 反代的端口号；示例 -port=8090
    -cn         : 使用 aliyun image 镜像，适用于 CN
    -y          : 覆盖已存在的文件
php maintain clear      # 删除由 maintain 生成的文件
    -y          : 确定删除，如果不提供则参数，则会打印待删除的文件
php maintain prod       # 将应用配置文件生成到 prod 目录下
    -dir[=Str]   : 保存目录，默认为 default；如果目录存在
    -c[=*]       : -c=* 时会 create 全部配置文件到 prod 目录；否则只会更新 ssh.php 文件
    -y           : 覆盖已经存在的配置文件（ssh.php 不会被覆盖）
    -r           : 使用 ssh.php 的信息来更新配置文件中的默认信息
    -u[=Str]     : 将 -dir 目录下的配置文件 upload 到 ssh.php 中服务器指定的项目位置；注意：需要安装 ssh2 扩展， apt install php8.2-ssh2 ssh
                   默认值为 *，表示同时上传 app, nginx, hosts
                   app   上传应用相关的配置文件
                   nginx 上传 nginx 相关的配置文件
                   hosts 修改 /etc/hosts 文件
    -del[=Str]   : 移除 -u 所上传的文件，默认值为 *，可选值为 app|nginx|hosts
    -d           : 下载 ssh.php 中远程项目的配置文件下载到 -dir 指定的本地目录，保存时到自动追加日期
    -log         : 下载 ssh.php 配置的日志文件到 prod/logs 目录下，保存时以 {-dir}/{Ymd}/ 为前缀
    -project=Str : 推送指定  project 到远程目录
HELP;
        echo PHP_EOL;
        break;
    default:
        die('unknown action!!' . PHP_EOL);
}

$g->saveMaintainTmp();

