site_name: "Phalcon admin docs"

nav:
  - 目录: "index.md"
  - 快速开始: "quick_start.md"
  - "模板 phtml": "layui_phtml.md"
# https://squidfunk.github.io/mkdocs-material/reference/admonitions/
markdown_extensions:
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences:
      # https://squidfunk.github.io/mkdocs-material/reference/diagrams/
      custom_fences:
        - name: mermaid
          class: mermaid
  - pymdownx.inlinehilite
  - pymdownx.details
  - admonition
  - tables
  - def_list
  # https://squidfunk.github.io/mkdocs-material/reference/lists/ 二级列表
  - pymdownx.tasklist:
      custom_checkbox: true
  # - attr_list
  # - pymdownx.emoji
  - pymdownx.tabbed:
      alternate_style: true
extra_javascript:
  - assets/highlight.min.js
  - assets/global.js
  - assets/mermaid.min.js
extra_css:
  - assets/highlight.min.css
  - assets/global.css
theme:
  name: material
  language: zh
  features:
    # - navigation.tabs
    # - navigation.sections # 重新组件目录，二级目录变顶级目录
    # - navigation.expand # 自动展开二级目录
    - content.tabs.link # 在新标签中打开链接
    - content.code.copy # 代码块右上角复制按钮
  highlightjs: true
  hljs_languages:
    - javascript
    - typscript
    - php
    - python
    - csharp
    - dart
extra:
  generator: false
plugins:
  - search
  - open-in-new-tab
