<?php

/**
 * @var \Phax\Helper\HtmlHelper $vv
 */
$form = \App\Modules\tao\TaoAppService::layuiForm();
?>
<form class="layui-form">
    <?php
    echo $form->groups([
            $form->input('应用名称', 'title',
                    value: $vv->pick('title', ''),
                    required: true, formItem: false),
            $form->checkbox('沙盒', 'sandbox',
                    checked: $vv->html()->pickBoolean('sandbox'), formItem: false)

    ]);
    echo $form->groups([
            $form->select('平台', 'platform',
                    vtOptions: \App\Modules\tao\Data\UserBindPlatform::MapPlatform,
                    value: $vv->pick('platform', 0), required: true, formItem: false),
            $form->select('类型', 'kind',
                    vtOptions: \App\Modules\tao\Data\UserBindPlatform::MapAppKinds,
                    value: $vv->pick('kind', ''), required: true, formItem: false),
    ]);

    echo $form->groups([
            $form->input('Appid', 'appid', value: $vv->pick('appid', ''),
                    required: true, formItem: false),
            $form->input('Secret', 'secret', value: $vv->pick('secret', ''),
                    required: true, formItem: false),
    ]);
    ?>

    <!-- 微信 -->
    <div>
        <?php
        echo $form->groups([
                $form->input('CropId', 'crop_id',
                        value: $vv->pick('crop_id', ''),
                        placeholder: '企业微信 cropId',
                        formItem: false),
                $form->input('Token', 'token',
                        value: $vv->pick('token', ''),
                        formItem: false)
        ]);

        echo $form->groups([
                $form->input('encMethod', 'enc_method',
                        value: $vv->pick('enc_method', ''),
                        placeholder: '消息加解密方式', formItem: false),
                $form->input('aesKey', 'aes_key',
                        value: $vv->pick('aes_key', ''),
                        placeholder: '消息加解密密钥', formItem: false)
        ]);
        ?>
    </div>

    <?php echo $form->textarea('备注', 'remark', value: $vv->pick('remark')) ?>


    <div class="hr-line"></div>
    <div class="layui-form-item text-center">
        <button type="submit" class="layui-btn layui-btn-normal layui-btn-sm" lay-submit>确认</button>
        <button type="reset" class="layui-btn layui-btn-primary layui-btn-sm">重置</button>
    </div>

</form>
<?php
\App\Modules\tao\TaoAppService::layui()->addWindowConfig()->footer(); ?>

<script>
    admin.form.submitFirst(() => {
        admin.iframe.close(true);
    }, function (data) {
        return Object.assign(data, {})
    })
</script>
