<?php
/**
 * @var \App\Modules\tao\Helper\MyMvcHelper $vv
 */

?>
<?php
if (file_exists(__DIR__ . '/welcome.main.phtml')) {
    include_once __DIR__ . '/welcome.main.phtml';
} else { ?>

    <h5>欢迎界面</h5>
    <?php
    if ($vv->isDemo()) { ?>
        <div class="text-danger" style="margin-top: 15px;">当前为演示系统，数据不定期清空，请不要填写重要数据</div>
        <?php
    } ?>
    <?php
    $vv->layui()->addWindowConfig([])->footer(); ?>
    <?php
} ?>
