<?php


/**
 * @var \Phax\Helper\HtmlHelper $vv
 */
$form = \App\Modules\tao\TaoAppService::layuiForm();
?>
<form class="layui-form" id="form">

    <?php

    echo $form->groups([
            $form->input('应用名称', 'title', value: $vv->pick('title'), required: true, formItem: false),
            $form->input('组名', 'tag', value: $vv->pick('tag'), formItem: false),
    ]);

    echo $form->textarea('备注', 'remark', value: $vv->pick('remark'));

    echo $form->submit();
    ?>
</form>
<?php
\App\Modules\tao\TaoAppService::layui()->addWindowConfig()->footer();
?>
<script>
    admin.form.submitFirst(() => {
        admin.iframe.close(true);
    })
</script>

