<?php

/**
 * @var \Phalcon\Mvc\View\Engine\AbstractEngine $this
 * @var \App\Modules\tao\Helper\MyMvcHelper $vv
 */
$console = $vv->html()->get('console', true); // 默认后台模板
$vv->layui();
?>
<!DOCTYPE html>
<html lang="zh">
<head>
    <meta charset="utf-8">
    <title><?php
        echo $vv->html()->title() ?></title>
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!--[if lt IE 9]>
    <script src="https://cdn.staticfile.org/html5shiv/r29/html5.min.js"></script>
    <script src="https://cdn.staticfile.org/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    <?php
    $vv->html()->outputHeaders();
    ?>
    <style><?php
        include __DIR__ . '/tao.css'; ?></style>
</head>
<body>
<div class="<?php
echo $console ? 'tao-container' : '' ?>">
    <?php
    echo $this->view->getContent(); ?>
</div>
</body>

<?php
$vv->html()->outputFooters();
$vv->layui()->footer();
$vv->appendTemplateJs();
?>

</html>