###############################################
# 1。根据你的实际情况修改 server_name, propxy_pass:port, log, ssl 路径
# 注意与 .env 中的相匹配
# 此文件放在服务器所在 nginx 的主机目录中中
# 2。将 server_name 添加到 /etc/nginx/conf.d/ 中
# 3。在系统 /etc/hosts 中添加对应的 server_name
###############################################
# 如果你使用 maintain 管理，那么此文件将作为模板使用，并生成新的配置文件

# myphpadmin
#server {
#    listen 80;
#    server_name db-xxx.test;
#    location / {
#    	proxy_set_header Host $http_host;
#        proxy_pass http://127.0.0.1:5456;
#    }
#}

server {
    listen 80;
    # 在这里添加更多的域名
    server_name xxx.test;
    include host.location.example.conf;
}

# 为指定域名添加证书
server {
	listen 443 ssl;
	server_name xxx.test;

	# ssl on;
	ssl_prefer_server_ciphers on;
	# for pem or crt file
	ssl_certificate 	conf.d/xxx.pem;
	ssl_certificate_key conf.d/xxx.key;
	ssl_protocols       TLSv1 TLSv1.1 TLSv1.2;
	ssl_ciphers         HIGH:!aNULL:!MD5;

    include host.location.example.conf;
}


