#access_log /data/log/phalcon/abc.test.log;
#error_log  /data/log/phalcon/abc.test.log;
location / {
    # 端口号需要与 .env OPEN_PORT 相配置
    proxy_pass http://127.0.0.1:8071;
    proxy_set_header Host $http_host;
    # 设置 X-Forwarded-For 头部以传递客户端的真实 IP 地址
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    # 真实 IP
    proxy_set_header X-Real-IP $remote_addr;
    # 设置 X-Forwarded-Host 头部以传递原始请求的 Host 头部
    proxy_set_header X-Forwarded-Host $host;

    # 还可以设置 X-Forwarded-Proto 头部以传递原始请求的协议（http 或 https）
    proxy_set_header X-Forwarded-Proto $scheme;
    # 端口号
    proxy_set_header X-Forwarded-Port $server_port;
    # 不需要知道原始连接信息
    proxy_set_header Connection '';
    # 自定义的头信息
    proxy_set_header X-Custom-Header $http_x_custom_header;

    # WebSocket 反向代理
    #proxy_set_header Upgrade $http_upgrade;
    #proxy_set_header Connection "upgrade";
}