#!/usr/bin/env php

<?php

const PATH_ROOT = __DIR__ . DIRECTORY_SEPARATOR;
require_once 'tao996/Kernel.php';

\tao996\Kernel::with(PATH_ROOT)
        ->setupDisplayErrors()
        ->createApplication()->runCLI();

