[supervisord]
nodaemon=true
user=root
logfile=/dev/stdout
logfile_maxbytes=0
pidfile=storage/app/supervisord.pid

[program:cli]
# workerman https://manual.workerman.net/doc/zh-cn/install/start-and-stop.html
# php index.php start 以 debug 方式启动； php index.php start -d 以守护进程方式启动
# php index.php stop 停止
# php index.php restart 重启
# php index.php reload 平滑重启
# php index.php status 查看状态
# php index.php connections 查看连接状态
#
command=php app/worker/index.php start
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
autorestart=true
startretries=5

[include]
files = /etc/supervisor/conf.d/*.conf